export const INITIAL_CATEGORIES: Category[] = [
  {
    id: "1",
    name: "Objetos",
    cards: [
      "Mesa",
      "Silla",
      "Cuchillo",
      "Tenedor",
      "Cuchara",
      "Plato",
      "Vaso",
      "Taza",
      "Ventana",
      "Puerta",
      "Lámpara",
      "Espejo",
      "Reloj",
      "Teléfono",
      "Tijeras",
      "Llave",
      "Candado",
      "Cepillo",
      "Peine",
      "Jabón",
      "Toalla",
      "Almohada",
      "Sábana",
      "Colchón",
      "Manta",
      "Computadora",
      "Teclado",
      "Ratón",
      "Auriculares",
      "Libro",
      "Cuaderno",
      "Bolígrafo",
      "Lápiz",
      "Goma de borrar",
      "Billete",
      "Moneda",
      "Cartera",
      "Mochila",
      "Paraguas",
      "Zapatos",
      "Anillo",
      "Collar",
      "Cámara",
      "Televisor",
      "Control Remoto",
      "Nevera",
      "Horno",
      "Micrófono",
      "Altavoz",
      "Bicicleta",
      "Guitarra",
      "Tambor",
      "Martillo",
      "Clavo",
      "Destornillador",
      "Cable",
      "Botella",
      "Jarrón",
      "Percha",
      "Mechero",
    ],
  },
  {
    id: "2",
    name: "Empresas",
    cards: [
      "Apple",
      "Google",
      "Amazon",
      "Microsoft",
      "Samsung",
      "Coca-Cola",
      "McDonald's",
      "Nike",
      "Adidas",
      "Disney",
      "Netflix",
      "Toyota",
      "Mercedes-Benz",
      "Sony",
      "Visa",
      "Mastercard",
      "Starbucks",
      "YouTube",
      "Tesla",
      "Ferrari",
      "TikTok",
      "Facebook",
      "Twitter",
      "LEGO",
      "Zara",
    ],
  },
  {
    id: "3",
    name: "Países",
    cards: [
      "Argentina",
      "Brasil",
      "México",
      "Chile",
      "España",
      "Estados Unidos",
      "Canadá",
      "Reino Unido",
      "Francia",
      "Alemania",
      "Italia",
      "Rusia",
      "China",
      "India",
      "Japón",
      "Corea del Sur",
      "Australia",
      "Egipto",
      "Sudáfrica",
      "Nigeria",
      "Arabia Saudita",
      "Portugal",
      "Países Bajos",
      "Bélgica",
      "Suecia",
      "Suiza",
      "Grecia",
      "Turquía",
      "Israel",
      "Emiratos Árabes",
      "Indonesia",
      "Tailandia",
      "Vietnam",
      "Perú",
      "Colombia",
      "Venezuela",
      "Cuba",
      "Puerto Rico",
      "Filipinas",
      "Pakistán",
      "Bangladesh",
      "Ucrania",
      "Polonia",
      "Irlanda",
      "Marruecos",
      "Kenia",
      "Nueva Zelanda",
      "Singapur",
      "Austria",
      "Dinamarca",
    ],
  },
  {
    id: "4",
    name: "Famosos",
    cards: [
      "Lionel Messi",
      "Cristiano Ronaldo",
      "Taylor Swift",
      "Beyoncé",
      "Leonardo DiCaprio",
      "Will Smith",
      "Brad Pitt",
      "Angelina Jolie",
      "Tom Hanks",
      "Dwayne Johnson",
      "Michael Jordan",
      "Serena Williams",
      "Roger Federer",
      "Diego Maradona",
      "Papa Francisco",
      "Shakira",
      "Adele",
      "Ed Sheeran",
      "Elon Musk",
      "Bill Gates",
      "Jeff Bezos",
      "Mark Zuckerberg",
      "Barack Obama",
      "Vladimir Putin",
      "Reina Isabel II",
      "Albert Einstein",
      "Mahatma Gandhi",
      "Martin Luther King Jr.",
      "Nelson Mandela",
      "Marilyn Monroe",
      "Madonna",
      "Elvis Presley",
      "The Beatles",
      "Michael Jackson",
      "Freddy Mercury",
      "Walt Disney",
      "Steven Spielberg",
      "Jackie Chan",
      "Bruce Lee",
      "Muhammad Ali",
      "Che Guevara",
      "Frida Kahlo",
      "Vincent van Gogh",
      "Pablo Picasso",
      "Stephen Hawking",
      "Greta Thunberg",
      "Malala Yousafzai",
      "Lady Gaga",
      "J-Hope",
      "Zendaya",
    ],
  },
  {
    id: "5",
    name: "Lugares",
    cards: [
      "Playa",
      "Montaña",
      "Desierto",
      "Bosque",
      "Cascada",
      "Cueva",
      "Océano",
      "Río",
      "Lago",
      "Zoológico",
      "Museo",
      "Estadio",
      "Teatro",
      "Biblioteca",
      "Coliseo Romano",
      "Torre Eiffel",
      "Pirámides de Giza",
      "Gran Muralla China",
      "Estatua de la Libertad",
      "Machu Picchu",
      "Cristo Redentor",
      "Taj Mahal",
      "Big Ben",
      "Plaza Roja",
      "Central Park",
      "Casa Rosada",
      "Obelisco",
      "Times Square",
      "La Meca",
      "La Luna",
      "Marte",
      "Hospital",
      "Escuela",
      "Comisaría",
      "Banco",
      "Aeropuerto",
      "Puerto",
      "Parque de diversiones",
      "Cementerio",
      "Cárcel",
      "Estación de tren",
      "Metro",
      "Cataratas del Niágara",
      "Palacio de Buckingham",
      "El Vaticano",
      "Acuario",
      "Volcán",
      "Glaciar",
      "Ciudad Perdida",
      "Gran Cañón",
    ],
  },
  {
    id: "6",
    name: "Animales",
    cards: [
      "Perro",
      "Gato",
      "León",
      "Tigre",
      "Elefante",
      "Jirafa",
      "Cebra",
      "Rinoceronte",
      "Hipopótamo",
      "Oso",
      "Lobo",
      "Zorro",
      "Ciervo",
      "Conejo",
      "Ardilla",
      "Mono",
      "Gorila",
      "Chimpancé",
      "Panda",
      "Koala",
      "Delfín",
      "Ballena",
      "Tiburón",
      "Pulpo",
      "Pez",
      "Serpiente",
      "Cocodrilo",
      "Tortuga",
      "Rana",
      "Pájaro",
      "Águila",
      "Búho",
      "Loro",
      "Pingüino",
      "Flamenco",
      "Vaca",
      "Caballo",
      "Oveja",
      "Cerdo",
      "Cabra",
      "Gallina",
      "Pato",
      "Ganso",
      "Camello",
      "Llama",
      "Canguro",
      "Murciélago",
      "Araña",
      "Mosquito",
      "Mariposa",
      "Abeja",
      "Hormiga",
      "Escorpión",
      "Caracol",
      "Grillo",
      "Puma",
      "Jaguar",
      "Leopardo",
      "Caimán",
      "Pez Payaso",
    ],
  },
];
